#!/bin/bash
# Store Type creation script using curl
# Generated by Doctool

set -e

# Configuration - set these variables before running
KEYFACTOR_HOSTNAME="${KEYFACTOR_HOSTNAME}"
KEYFACTOR_API_PATH="${KEYFACTOR_API_PATH:-KeyfactorAPI}"
KEYFACTOR_AUTH_TOKEN="${KEYFACTOR_AUTH_TOKEN}"

echo "Creating store type: Kemp"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "Kemp",
  "ShortName": "Kemp",
  "Capability": "Kemp",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "Not used."
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "Kemp Api Password. (or valid PAM key if the username is stored in a KF Command configured PAM integration)."
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true,
      "IsPAMEligible": false,
      "Description": "Should be true, http is not supported."
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}'

